server:
  port: 0

spring:
  application:
    name: email-send-consumer
  kafka:
    bootstrap-servers: 43.200.183.198:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      auto-offset-reset: earliest  # 컨슈머 그룹이 없으면 컨슈머 그룹 직접 생성 및 --from-beginning 옵션 실행
