spring:
    kafka:
        bootstrap-servers: 3.34.90.182:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            properties:
                partitioner.class: org.apache.kafka.clients.producer.RoundRobinPartitioner