server:
    port: 8080

spring:
    kafka:
        bootstrap-servers:
            - 3.34.90.182:9092
            - 3.34.90.182:19092
            - 3.34.90.182:29092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            properties:
                partitioner.class: org.apache.kafka.clients.producer.RoundRobinPartitioner

    h2:
        console:
            enabled: true

    datasource:
        url: jdbc:h2:mem:userDB
        driverClassName: org.h2.Driver
        username: sa
        password:
