server :
    port : 8081
spring:
    h2:
        console:
            enabled: true

    datasource:
        url: jdbc:h2:mem:emailDB
        username: sa
        password:
        driver-class-name: org.h2.Driver
    
    kafka:
        bootstrap-servers:
            - 3.34.90.182:9092
            - 3.34.90.182:19092
            - 3.34.90.182:29092
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            auto-offset-reset: earliest